# Global Costmap Parameters
global_costmap:
  ros__parameters:
    update_frequency: 5.0
    publish_frequency: 2.0
    global_frame: "map"
    robot_base_frame: "base_link"
    resolution: 0.05
    width: 10.0
    height: 10.0
    footprint: "[[0.2, 0.2], [-0.2, 0.2], [-0.2, -0.2], [0.2, -0.2]]"
    robot_radius: 0.15
    inflation_radius: 0.1
    plugins: ["camera_obstacle_layer", "inflation_layer", "obstacle_layer"]

    camera_obstacle_layer:
      plugin: "package_name::CameraObstacleLayer"
      enabled: true
      # Additional parameters such as topic name or specific thresholds

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true
      inflation_radius: 0.1

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: scan
      scan:
        topic: "/scan"
        expected_update_rate: 10.0  # Rate in Hz
        marking: true
        clearing: true
        max_obstacle_height: 2.0
        min_obstacle_height: 0.0

# Local Costmap Parameters
local_costmap:
  ros__parameters:
    update_frequency: 10.0
    publish_frequency: 5.0
    global_frame: "odom"
    robot_base_frame: "base_link"
    resolution: 0.05
    width: 10.0
    height: 10.0
    footprint: "[[0.2, 0.2], [-0.2, 0.2], [-0.2, -0.2], [0.2, -0.2]]"
    robot_radius: 0.15
    inflation_radius: 0.1
    plugins: ["camera_obstacle_layer", "inflation_layer", "obstacle_layer"]

    camera_obstacle_layer:
      plugin: "package_name::CameraObstacleLayer"
      enabled: true
      # Possibly different parameters or thresholds for local processing

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true
      inflation_radius: 0.1

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: scan
      scan:
        topic: "/scan"
        expected_update_rate: 10.0
        marking: true
        clearing: true
        max_obstacle_height: 2.0
        min_obstacle_height: 0.0
